import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const main = async () => {
  try {
    await prisma.match.deleteMany();
    console.log("Matches deleted");

    await prisma.match.createMany({
      data: [
        {
          homeTeamCode: "QAT",
          awayTeamCode: "ECU",
          date: "2022-11-20T16:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Group_Stage",
          code: "group-a_qat-ecu",
        },
        {
          homeTeamCode: "ENG",
          awayTeamCode: "IRN",
          date: "2022-11-21T13:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Group_Stage",
          code: "group-b_eng-irn",
        },
        {
          homeTeamCode: "SEN",
          awayTeamCode: "NED",
          date: "2022-11-21T16:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Group_Stage",
          code: "group-a_sen-ned",
        },
        {
          homeTeamCode: "USA",
          awayTeamCode: "WAL",
          date: "2022-11-21T19:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Ahmad Bin Ali Stadium",
          stage: "Group_Stage",
          code: "group-b_usa-wal",
        },
        {
          homeTeamCode: "ARG",
          awayTeamCode: "KSA",
          date: "2022-11-22T10:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Group_Stage",
          code: "group-c_arg-ksa",
        },
        {
          homeTeamCode: "DEN",
          awayTeamCode: "TUN",
          date: "2022-11-22T13:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Group_Stage",
          code: "group-d_den-tun",
        },
        {
          homeTeamCode: "MEX",
          awayTeamCode: "POL",
          date: "2022-11-22T16:00:00Z",
          location: "Doha",
          stadium: "Stadium 974",
          stage: "Group_Stage",
          code: "group-c_mex-pol",
        },
        {
          homeTeamCode: "FRA",
          awayTeamCode: "AUS",
          date: "2022-11-22T19:00:00Z",
          location: "Al Wakrah",
          stadium: "Al Janoub Stadium",
          stage: "Group_Stage",
          code: "group-d_fra-aus",
        },
        {
          homeTeamCode: "MAR",
          awayTeamCode: "CRO",
          date: "2022-11-23T10:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Group_Stage",
          code: "group-f_mar-cro",
        },
        {
          homeTeamCode: "GER",
          awayTeamCode: "JPN",
          date: "2022-11-23T13:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Group_Stage",
          code: "group-e_ger-jpn",
        },
        {
          homeTeamCode: "ESP",
          awayTeamCode: "CRC",
          date: "2022-11-23T16:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Group_Stage",
          code: "group-e_esp-crc",
        },
        {
          homeTeamCode: "BEL",
          awayTeamCode: "CAN",
          date: "2022-11-23T19:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Ahmad Bin Ali Stadium",
          stage: "Group_Stage",
          code: "group-f_bel-can",
        },
        {
          homeTeamCode: "SUI",
          awayTeamCode: "CMR",
          date: "2022-11-24T10:00:00Z",
          location: "Al Wakrah",
          stadium: "Al Janoub Stadium",
          stage: "Group_Stage",
          code: "group-g_sui-cmr",
        },
        {
          homeTeamCode: "URU",
          awayTeamCode: "KOR",
          date: "2022-11-24T13:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Group_Stage",
          code: "group-h_uru-kor",
        },
        {
          homeTeamCode: "POR",
          awayTeamCode: "GHA",
          date: "2022-11-24T16:00:00Z",
          location: "Doha",
          stadium: "Stadium 974",
          stage: "Group_Stage",
          code: "group-h_por-gha",
        },
        {
          homeTeamCode: "BRA",
          awayTeamCode: "SRB",
          date: "2022-11-24T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Group_Stage",
          code: "group-g_bra-srb",
        },
        {
          homeTeamCode: "WAL",
          awayTeamCode: "IRN",
          date: "2022-11-25T10:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Ahmad Bin Ali Stadium",
          stage: "Group_Stage",
          code: "group-b_wal-irn",
        },
        {
          homeTeamCode: "QAT",
          awayTeamCode: "SEN",
          date: "2022-11-25T13:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Group_Stage",
          code: "group-a_qat-sen",
        },
        {
          homeTeamCode: "NED",
          awayTeamCode: "ECU",
          date: "2022-11-25T16:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Group_Stage",
          code: "group-a_ned-ecu",
        },
        {
          homeTeamCode: "ENG",
          awayTeamCode: "USA",
          date: "2022-11-25T19:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Group_Stage",
          code: "group-b_eng-usa",
        },
        {
          homeTeamCode: "TUN",
          awayTeamCode: "AUS",
          date: "2022-11-26T10:00:00Z",
          location: "Al Wakrah",
          stadium: "Al Janoub Stadium",
          stage: "Group_Stage",
          code: "group-d_tun-aus",
        },
        {
          homeTeamCode: "POL",
          awayTeamCode: "KSA",
          date: "2022-11-26T13:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Group_Stage",
          code: "group-c_pol-ksa",
        },
        {
          homeTeamCode: "FRA",
          awayTeamCode: "DEN",
          date: "2022-11-26T16:00:00Z",
          location: "Doha",
          stadium: "Stadium 974",
          stage: "Group_Stage",
          code: "group-d_fra-den",
        },
        {
          homeTeamCode: "ARG",
          awayTeamCode: "MEX",
          date: "2022-11-26T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Group_Stage",
          code: "group-c_arg-mex",
        },
        {
          homeTeamCode: "JPN",
          awayTeamCode: "CRC",
          date: "2022-11-27T10:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Ahmad Bin Ali Stadium",
          stage: "Group_Stage",
          code: "group-e_jpn-crc",
        },
        {
          homeTeamCode: "BEL",
          awayTeamCode: "MAR",
          date: "2022-11-27T13:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Group_Stage",
          code: "group-f_bel-mar",
        },
        {
          homeTeamCode: "CRO",
          awayTeamCode: "CAN",
          date: "2022-11-27T16:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Group_Stage",
          code: "group-f_cro-can",
        },
        {
          homeTeamCode: "ESP",
          awayTeamCode: "GER",
          date: "2022-11-27T19:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Group_Stage",
          code: "group-e_esp-ger",
        },
        {
          homeTeamCode: "CMR",
          awayTeamCode: "SRB",
          date: "2022-11-28T10:00:00Z",
          location: "Al Wakrah",
          stadium: "Al Janoub Stadium",
          stage: "Group_Stage",
          code: "group-g_cmr-srb",
        },
        {
          homeTeamCode: "KOR",
          awayTeamCode: "GHA",
          date: "2022-11-28T13:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Group_Stage",
          code: "group-h_kor-gha",
        },
        {
          homeTeamCode: "BRA",
          awayTeamCode: "SUI",
          date: "2022-11-28T16:00:00Z",
          location: "Doha",
          stadium: "Stadium 974",
          stage: "Group_Stage",
          code: "group-g_bra-sui",
        },
        {
          homeTeamCode: "POR",
          awayTeamCode: "URU",
          date: "2022-11-28T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Group_Stage",
          code: "group-h_por-uru",
        },
        {
          homeTeamCode: "NED",
          awayTeamCode: "QAT",
          date: "2022-11-29T15:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Group_Stage",
          code: "group-a_ned-qat",
        },
        {
          homeTeamCode: "ECU",
          awayTeamCode: "SEN",
          date: "2022-11-29T15:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Group_Stage",
          code: "group-a_ecu-sen",
        },
        {
          homeTeamCode: "IRN",
          awayTeamCode: "USA",
          date: "2022-11-29T19:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Group_Stage",
          code: "group-b_irn-usa",
        },
        {
          homeTeamCode: "WAL",
          awayTeamCode: "ENG",
          date: "2022-11-29T19:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Ahmad Bin Ali Stadium",
          stage: "Group_Stage",
          code: "group-b_wal-eng",
        },
        {
          homeTeamCode: "TUN",
          awayTeamCode: "FRA",
          date: "2022-11-30T15:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Group_Stage",
          code: "group-d_tun-fra",
        },
        {
          homeTeamCode: "AUS",
          awayTeamCode: "DEN",
          date: "2022-11-30T15:00:00Z",
          location: "Al Wakrah",
          stadium: "Al Janoub Stadium",
          stage: "Group_Stage",
          code: "group-d_aus-den",
        },
        {
          homeTeamCode: "POL",
          awayTeamCode: "ARG",
          date: "2022-11-30T19:00:00Z",
          location: "Doha",
          stadium: "Stadium 974",
          stage: "Group_Stage",
          code: "group-c_pol-arg",
        },
        {
          homeTeamCode: "KSA",
          awayTeamCode: "MEX",
          date: "2022-11-30T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Group_Stage",
          code: "group-c_ksa-mex",
        },
        {
          homeTeamCode: "CRO",
          awayTeamCode: "BEL",
          date: "2022-12-01T15:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Ahmad Bin Ali Stadium",
          stage: "Group_Stage",
          code: "group-f_cro-bel",
        },
        {
          homeTeamCode: "CAN",
          awayTeamCode: "MAR",
          date: "2022-12-01T15:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Group_Stage",
          code: "group-f_can-mar",
        },
        {
          homeTeamCode: "CRC",
          awayTeamCode: "GER",
          date: "2022-12-01T19:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Group_Stage",
          code: "group-e_crc-ger",
        },
        {
          homeTeamCode: "JPN",
          awayTeamCode: "ESP",
          date: "2022-12-01T19:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Group_Stage",
          code: "group-e_jpn-esp",
        },
        {
          homeTeamCode: "KOR",
          awayTeamCode: "POR",
          date: "2022-12-02T15:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Group_Stage",
          code: "group-h_kor-por",
        },
        {
          homeTeamCode: "GHA",
          awayTeamCode: "URU",
          date: "2022-12-02T15:00:00Z",
          location: "Al Wakrah",
          stadium: "Al Janoub Stadium",
          stage: "Group_Stage",
          code: "group-h_gha-uru",
        },
        {
          homeTeamCode: "SRB",
          awayTeamCode: "SUI",
          date: "2022-12-02T19:00:00Z",
          location: "Doha",
          stadium: "Stadium 974",
          stage: "Group_Stage",
          code: "group-g_srb-sui",
        },
        {
          homeTeamCode: "CMR",
          awayTeamCode: "BRA",
          date: "2022-12-02T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Group_Stage",
          code: "group-g_cmr-bra",
        },
        {
          date: "2022-12-03T15:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Round_16",
          code: "r-16-a",
        },
        {
          date: "2022-12-03T19:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Ahmad Bin Ali Stadium",
          stage: "Round_16",
          code: "r-16-b",
        },
        {
          date: "2022-12-04T15:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Round_16",
          code: "r-16-c",
        },
        {
          date: "2022-12-04T19:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Round_16",
          code: "r-16-d",
        },
        {
          date: "2022-12-05T15:00:00Z",
          location: "Al Wakrah",
          stadium: "Al Janoub Stadium",
          stage: "Round_16",
          code: "r-16-e",
        },
        {
          date: "2022-12-05T19:00:00Z",
          location: "Doha",
          stadium: "Stadium 974",
          stage: "Round_16",
          code: "r-16-f",
        },
        {
          date: "2022-12-06T15:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Round_16",
          code: "r-16-g",
        },
        {
          date: "2022-12-06T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Round_16",
          code: "r-16-h",
        },
        {
          date: "2022-12-09T15:00:00Z",
          location: "Doha",
          stadium: "Education City Stadium",
          stage: "Quarter_Final",
          code: "qf-a",
        },
        {
          date: "2022-12-09T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Quarter_Final",
          code: "qf-b",
        },
        {
          date: "2022-12-10T15:00:00Z",
          location: "Doha",
          stadium: "Al Thumama Stadium",
          stage: "Quarter_Final",
          code: "qf-c",
        },
        {
          date: "2022-12-10T19:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Quarter_Final",
          code: "qf-d",
        },
        {
          date: "2022-12-13T19:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Semi_Final",
          code: "sf-a",
        },
        {
          date: "2022-12-14T19:00:00Z",
          location: "Al Khor",
          stadium: "Al Bayt Stadium",
          stage: "Semi_Final",
          code: "sf-b",
        },
        {
          date: "2022-12-17T15:00:00Z",
          location: "Ar-Rayyan",
          stadium: "Khalifa International Stadium",
          stage: "Third_Place",
          code: "tp",
        },
        {
          date: "2022-12-18T15:00:00Z",
          location: "Al Daayen",
          stadium: "Lusail Stadium",
          stage: "Final",
          code: "final",
        },
      ],
    });
    console.log("Matches created");
  } catch (error) {
    console.error(error);
  } finally {
    await prisma.$disconnect();
  }
};

main();
